#!name=Extended-rules
#!desc=extended rules & defined groupings

[Rule]

DOMAIN-SUFFIX,chatgpt.ch,NIGERIAAPP
DOMAIN-SUFFIX,chatgpt.ai,NIGERIAAPP
DOMAIN-SUFFIX,chatgpt.com,NIGERIAAPP
DOMAIN-SUFFIX,chatgpt-robot.ru,NIGERIAAPP
DOMAIN-SUFFIX,chatgpt.tool00.com,NIGERIAAPP
DOMAIN-SUFFIX,chatgpt.org,NIGERIAAPP
DOMAIN-SUFFIX,chatgpt.nextweb.fun,NIGERIAAPP
DOMAIN-SUFFIX,chatgpt1.nextweb.fun,NIGERIAAPP
DOMAIN-SUFFIX,chatgpt4online.org,NIGERIAAPP
DOMAIN-SUFFIX,chatgptweb.ru,NIGERIAAPP
DOMAIN-SUFFIX,freechatgpt.chat,NIGERIAAPP
DOMAIN-SUFFIX,auth0.openai.com,NIGERIAAPP
DOMAIN-SUFFIX,openai.com,NIGERIAAPP
DOMAIN-SUFFIX,chat.openai.com,NIGERIAAPP
DOMAIN-SUFFIX,api.openai.com,NIGERIAAPP

DOMAIN-SUFFIX,anthropic.com,NIGERIAAPP
DOMAIN-SUFFIX,claude.ai,NIGERIAAPP
DOMAIN-SUFFIX,claude.com,NIGERIAAPP

DOMAIN-SUFFIX,themoviedb.org,PROXY
DOMAIN-SUFFIX,remini.ai,PROXY
DOMAIN-SUFFIX,api-livevideocall.7seasol.in,PROXY
